# Generated by Django 5.2.8 on 2026-09-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='flagged',
            field=models.BooleanField(default=True),
        ),
    ]
