# Generated by Django 5.2.8 on 2026-09-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
